### PR TITLE
Convert to a pure ESM package

### PR DESCRIPTION
**Pull request by jonkoops**
Converts to a [pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). This is needed for modern tooling that no longer supports CommonJS such as [Web Test Runner](https://modern-web.dev/docs/test-runner/overview/), which we intend to use for Leaflet.

This removes support for consuming this package in any other type of module format, making this a breaking change. This PR also:

- Removes the build step entirely, instead shipping code directly from source.
- Adds a Dependabot configuration to keep the little dependencies we have up-to-date.
- Replaces ingored files from `.npmignore` with the explicit [`files`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files) field.
- Refactors all of the demo HTML pages to use ESM.
- Moves all the source from `src` to `lib`.

### CODE REVIEW

**Comment by jonkoops** [comment]
Before releasing the work in this PR we might want to remove some old browser code and polyfills.

**Comment by IvanSanchez** [comment]
> Before releasing the work in this PR we might want to remove some old browser code and polyfills.

Yeah, sounds like the sane thing to do on a new major version number. I'll have a shot at it.

**Comment by IvanSanchez** [comment]
See https://github.com/jonkoops/prosthetic-hand/pull/1

**Comment by jonkoops** [comment]
@IvanSanchez can we merge the PR as-is and create some new PRs to clean up the rest? I'd like to avoid this one getting too chunky.

**Pull request merged**
